apiVersion: apps/v1
kind: Deployment
metadata:
  name: conv-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: conv-api
  template:
    metadata:
      labels:
        app: conv-api
    spec:
      containers:
      - name: conv-api
        image: antonlarichev/short-api:v.0
        imagePullPolicy: Always
        env:
        - name: AMQP_EXCHANGE
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: AMQP_EXCHANGE
        - name: SEED_USER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: SEED_USER_PASSWORD
        - name: SEED_USERNAME
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: SEED_USERNAME
        - name: AMQP_HOSTNAME
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: AMQP_HOSTNAME
        resources:
          limits:
            memory: "500i"
            cpu: "200m"
        ports:
        - containerPort: 80
