apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.app.name }}-clusterip"
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.app.name }}
  ports:
  - port: {{ .Values.app.port }}
    targetPort: 80
    protocol: TCP