apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
spec:
  replicas: { .Values.app.replicas }
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
      - name: {{ .Values.app.name }}
        image: antonlarichev/short-app:v1.4
        imagePullPolicy: Always
        env:
        - name: AMQP_QUEUE
          valueFrom:
            secretKeyRef:
              name: conv-api-secret
              key: AMQP_QUEUE
        - name: VITE_DOMAIN
          valueFrom:
            configMapKeyRef:
              name: conv-app-configmap
              key: VITE_DOMAIN
        resources:
          limits: {{ .Values.limits | toYaml | nindent 14 }}
        ports:
        - containerPort: 80
